### ISSUE TITLE
Get CSFR Monthly input data

### ISSUE THREAD

**Issue by windnagelnsidc** [nsidc/sipn-reanalysis-ingest#21]
Need to gather CFSR data (monthly) 
• Air temp : `T` variable in netcdf
o 925mb : level 1
o 850mb : level 2
o 500mb : level 3
o Sfc : `T2m`
• SLP : `MSLP` (sea level only)
• Geopotential height : `HGT`
o 925mb : see air temp for levels
o 850mb 
o 500mb 
• U and V winds : `U`, `V`
o 925mb : see air temp for levels
o 850mb 
o 500mb 
o Sfc : `U10m`, `V10m`
• Humidity variables
o Specific : `SH` (has levels in the style of air temp, `SH2m` is surface)
o Relative :  `RH` (has levels in the style of air temp, `RH2m` is surface)
• Precipitable water : `PWAT`
• OI SST : TBD. We think it's in a different dataset

CFSR2 – 1/1/11 – present 
CFSR1 – 1/1/79-12/31/10 

Note: `*2m` variables are "surface" level data.

# Task list

- [x] Download full monthly datasets to Liz's machine 
- [x] Determine how much storage is needed (worst case scenario): 135GB for the monthly + daily data
- [x] How much data comes in each month? Input tars are 746MB for v2. Output NetCDF: **8MB / month**
- [x] Request storage from SA
- [ ] Merge all parameters into one 3d variable (e.g. one air temp variable with 4 levels including surface level)
- [ ] Compute wind velocity as angle and velocity vector components in addition to U and V (can matplotlib plot vector data from angle and velocity?)

Regarding monthly data -> The v1 monthly data is in yearly .tar files. There is a 1-year tar for analysis data (prefix `pgbhnl*`) and 1-year tar for forecast (prefix `pgbh06*`). v1 data has suffix `.grb2`. The v2 monthly data is in monthly .tar files that contain both analysis and forecast data (prefix `pgbh*`). v2 data has suffix `.grib2`. All the v2 monthly forecast files will contain forecast ranges we're not interested in (1-hour through 5-hour) that will need to be deselected, keeping 6-hour forecasts.

# Acceptance criteria

- [x] Correct product
- [ ] Move into NSIDC storage
- [x] Subset to 40 N Latitude
- [ ] Reproject to EPSG:3413
