### ISSUE TITLE
Get Daily CFSR as input data

### ISSUE THREAD

**Issue by encassano** [nsidc/sipn-reanalysis-ingest#3]
Get reanalysis data from CSFR: https://rda.ucar.edu/ 

```
Need to gather CFSR data (daily) 
• Air temp : `T` variable in netcdf
o 925mb : level 1
o 850mb : level 2
o 500mb : level 3
o Sfc : `T2m`
• SLP : `MSLP` (sea level only)
• Geopotential height : `HGT`
o 925mb : see air temp for levels
o 850mb 
o 500mb 
• U and V winds : `U`, `V`
o 925mb : see air temp for levels
o 850mb 
o 500mb 
o Sfc : `U10m`, `V10m`
• Humidity variables
o Specific : `SH` (has levels in the style of air temp, `SH2m` is surface)
o Relative :  `RH` (has levels in the style of air temp, `RH2m` is surface)
• Precipitable water : `PWAT`
• OI SST : TBD. We think it's in a different dataset

CFSR2 – 1/1/11 – present 
CFSR1 – 1/1/79-12/31/10 
```

Note: `*2m` variables are "surface" level data.

# Task list

- [ ] Download full daily and monthly datasets to Liz's machine 
- [x] Determine how much storage is needed (worst case scenario): _135G__
- [x] How much data comes in each day: _See comment below the task list__
- [ ] Request storage from SA
- [x] Merge all parameters into one 3d variable (e.g. one air temp variable with 4 levels including surface level)
- [x] Compute wind velocity as angle and velocity vector components in addition to U and V (can matplotlib plot vector data from angle and velocity?)

Regarding daily data -> The data is stored in 5 day tar files (even if one only requests 1 day). We need 2 different tar files for each day of data so those are 3G total (1.5G each). Then they have to be untarred and processed, so I would estimate needing about 5-7G of space for this process. But each daily netcdf file that is the result of this is 8M.

# Acceptance criteria

- [ ] Correct product
- [ ] Move into NSIDC storage
- [x] Subset to 40 N Latitude
- [ ] Reproject to `EPSG:3413`
